### ISSUE TITLE
[007] Cadastro de usuários

### ISSUE THREAD

**Issue by yurihs** [yurihs/sistema-portuario#11]
O sistema deve permitir que administradores cadastrem usuários, com nome, CPF, email, senha e tipo de usuário.

- [x] Backend
- [ ] Interface de Criação #48 
- [ ] Interface de Exibição com botão de remoção #49 
- [ ] Interface de Alteração #50 
- [ ] Interface de Listagem #51
